apiVersion: v2
name: user-service
description: VeXeViet User Service Helm Chart
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - vexeviet
  - user-service
  - microservice
maintainers:
  - name: VeXeViet Team
